DC-14 write test for src/config
finaldream/decoupled pull request #9
Opened 2018-09-04 20:31 UTC by friendken

ref: https://finaldream.atlassian.net/browse/DC-14

2018-09-06 05:36 UTC, olivererdmann commented on packages/decoupled/jest.config.js
> +    "node"
@friendken Do we need `node` and `json`?

2018-09-06 05:36 UTC, olivererdmann commented on packages/decoupled/src/config/__tests__/config/default/default.js
> +module.exports.default = {
@friendken What's this?

2018-09-06 05:37 UTC, olivererdmann commented on packages/decoupled/src/config/__tests__/config/example/example.js
> +module.exports.example = {
@friendken ... and this?

2018-09-06 05:51 UTC, olivererdmann commented on packages/decoupled/src/config/provide-config.ts
> +export function readConfigFromFiles(configDir: string, pattern: RegExp): AnyObject {
@friendken Those are actually private functions, which shouldn't be exposed to the public API. 
I'd suggest one of the two things: 
1. the cleanest solution would be to put them into separate modules, which are not part of the public API. That way you can test them internally, but don't need to expose them. 
2. there is something called `rewire` around like this: https://github.com/speedskater/babel-plugin-rewire i could be used for accessing internals for testing, but I'd opt for the cleaner solution from above unless there's no other way.

2018-09-06 05:53 UTC, olivererdmann commented on packages/decoupled/src/config/__tests__/decoupledJson.test.ts
> +import {
@friendken Please colocate tests, don't use a separate `__tests__`-folder. Instead, do:
```
packages/decoupled/src/config/decoupledJson.ts
packages/decoupled/src/config/decoupledJson.test.ts
... and so on ...
```

2018-09-06 05:54 UTC, olivererdmann commented on packages/decoupled/src/config/__tests__/decoupledJson.test.ts
> +describe('this is hasDecoupledJson function test', () => {
@friendken `'this is hasDecoupledJson function test'` Really? 😂

2018-09-06 05:56 UTC, olivererdmann commented on packages/decoupled/src/config/__tests__/decoupledJson.test.ts
> +        expect(hasDecoupledJson()).toBe(false);
@friendken Does this test really make sense? What about a positive test?

2018-09-06 07:15 UTC, olivererdmann commented on packages/decoupled/src/config/__tests__/decoupledJson.test.ts
> +        expect(result).toBe('./');
@friendken Can you please be more elaborate? I.e. this is just testing the default-value, there should also be a test about getting actual values.

2018-09-09 11:23 UTC, olivererdmann requested changes

2018-09-09 11:23 UTC, olivererdmann commented on packages/decoupled/src/config/__tests__/decoupledJson.test.ts
> +describe('this is getFromDecoupledJson function test', () => {
@friendken usually, you would just use a description like `getFromDecoupledJson()` to group all cases.

2018-09-09 11:23 UTC, olivererdmann commented on packages/decoupled/src/config/__tests__/config/default/default.js
> +module.exports.default = {
Ok i see it now, it's should represent the test-configuration, right? So then please put it in a folder called `fixtures`, so it's more obvious.

2018-09-09 11:23 UTC, olivererdmann commented on packages/decoupled/src/config/__tests__/get-site-ids.test.ts
> +describe('this is getSiteIds function test', () => {
Please just use `getSiteIds()`

2018-09-09 11:23 UTC, olivererdmann commented on packages/decoupled/src/config/__tests__/get-site-ids.test.ts
> +    expect(siteIds.includes('example')).toBe(true);
Jest provides more specific methods like [expect.arrayContaining](https://jestjs.io/docs/en/expect#expectarraycontainingarray)

2018-09-09 11:23 UTC, olivererdmann commented on packages/decoupled/src/config/__tests__/get-site-ids.test.ts
> +      expect(error.toString()).toEqual("Error: ENOENT: no such file or directory, scandir '/Users/friendken/Sites/decoupled/packages/decoupled/src/config/__tests__/something/'");
https://jestjs.io/docs/en/expect#tothrowerror

2018-09-09 11:23 UTC, olivererdmann commented on packages/decoupled/src/config/__tests__/get-site-ids.test.ts
> +  test('expect getSiteIds return an array of site with wrong rootPath', () => {
The description is misleading, should be something like `should throw error when ...`

2018-09-09 11:23 UTC, olivererdmann commented on packages/decoupled/src/config/__tests__/get-site-ids.test.ts
> +    // expect(siteIds.includes('example')).toBe(true);
@friendken please remove

2018-09-09 11:23 UTC, olivererdmann commented on packages/decoupled/src/config/__tests__/provide-config.test.ts
> +import path from 'path';
@friendken please prefer `import {join, resolve} from 'path';`

2018-09-09 11:23 UTC, olivererdmann commented on packages/decoupled/src/config/__tests__/provide-config.test.ts
> +        expect(new RegExp(filePattern)).toEqual(/^([^.]*.(moneyonmymind.de.js)$)/);
@friendken Please don't mention clients in public repos

2018-09-09 11:23 UTC, olivererdmann commented on packages/decoupled/src/config/decoupledJson.test.ts
> +    test('should return appPath value', () => {
@friendken Can we have another test from the existing `src/fixtures/decoupled.json`?

2018-09-09 11:23 UTC, olivererdmann commented on packages/decoupled/src/config/decoupledJson.ts
> +        decoupledJson = rootPath ? require(resolve(rootPath, 'decoupled.json')) : require(resolve('decoupled.json'));
@friendken what about this?
```
decoupledJson = require(resolve(rootPath || '', 'decoupled.json'));	     
```

2018-09-09 11:23 UTC, olivererdmann commented on packages/decoupled/src/config/decoupledJson.test.ts
> +    test('should return appPath value', () => {
to avoid adding another argument to `getFromDecoupledJson`, you could just call `loadDecoupledJson('src/fixtures')` before the test

2018-09-09 11:23 UTC, olivererdmann commented on packages/decoupled/src/config/get-site-ids.test.ts
> +    } catch (error) {
@friendken What about Jest's `toThrowError()`, wouldn't it be more effective than try-catch?

2018-09-09 11:23 UTC, olivererdmann commented on packages/decoupled/src/config/provide-config.test.ts
> +        const env = process.env.NODE_ENV;
@friendken I'd suggest hardcoding the `env`-value for tests and probably test more then just one value. If you rely on an external environment variable, the results might vary and might be not as expected.

2018-09-09 11:23 UTC, olivererdmann commented on packages/decoupled/src/config/provide-config.test.ts
> +        const env = process.env.NODE_ENV;
@friendken see above

2018-09-10 16:08 UTC, friendken commented on packages/decoupled/src/config/get-site-ids.test.ts
> +    } catch (error) {
I used try catch because the `fs.readdirSync` function not catch the error, it throw error and break response result

2018-09-10 16:22 UTC, friendken commented on packages/decoupled/src/config/decoupledJson.test.ts
> +    test('should return appPath value', () => {
I think the test of `hasDecoupledJson()` is already set the `decoupledJson` variable in decoupledJson.ts

2022-05-10 07:14 UTC, closed without merging